name: Crystal CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-format:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:0.35.1
    steps:
      - uses: actions/checkout@v1
      - name: Install shards
        run: shards install --ignore-crystal-version
      - name: Format
        run: crystal tool format --check
      - name: Lint
        run: ./bin/ameba
  build-linux:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:0.35.1
    steps:
    - uses: actions/checkout@v2
    - name: Install Chrome browser
      run: apt update && apt install -y chromium-browser
    - name: Install dependencies
      run: shards install --ignore-crystal-version
    - name: Run tests
      run: crystal spec
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Crystal
      run: brew update && brew install crystal
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
