name: Crystal CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install library for fixing MeilCli
      run: sudo apt-get install -y ruby-molinillo
    - uses: MeilCli/setup-crystal-action@v2
      with: 
        crystal_version: 0.34.0
        shards_version: latest
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: MeilCli/setup-crystal-action@v2
      with: 
        crystal_version: 0.34.0
        shards_version: latest
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
